### ISSUE TITLE
404 error for Getting Started: HTML Processor link

### ISSUE THREAD

**Issue by jplew** [dmbaturin/soupault-website#3]
Hi, I'm looking to get started and I noticed that this link gives a "Page Not Found":
https://soupault.app/getting-started-html-processor

![image](https://user-images.githubusercontent.com/462836/114143726-200bf080-9932-11eb-8981-b9d464d45f83.png)

**Comment by dmbaturin** [comment]
Indeed, I forgot to update that link when I moved the page to the "tips and tricks" section. Fixed now, thanks!
